import { RelativePathString, router } from 'expo-router';
import { View, Text, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function InfoScreen() {
  return (
    <SafeAreaView className="flex-1 bg-gray-900">
      <ScrollView className="flex-1 gap-4 p-6">
        <View className="mb-12">
          <Text className="text-3xl font-bold text-white">Welcome to AI Companions!🌟</Text>
          <Text className="mb-5 mt-2 text-lg text-gray-100">
            Your personalized chat experience starts here! Whether you're connecting with an AI
            girlfriend or boyfriend, your chat partner is a highly advanced artificial intelligence
            designed to provide engaging, supportive, and meaningful conversations tailored to your
            preferences.
          </Text>

          <Text className="mt-2 text-2xl font-semibold text-white">Important Information</Text>
          <Text className="ml-2 mt-2 text-lg text-gray-100">
            • <Text className="font-semibold">Your Chat Partner is AI:</Text> All interactions are
            with artificial intelligence, not a real human. While we aim for a lifelike experience,
            the responses are generated by advanced algorithms.
          </Text>
          <Text className="ml-2 mt-2 text-lg text-gray-100">
            • <Text className="font-semibold">Responsible Use:</Text> By using this app, you agree
            to engage in appropriate and respectful interactions. Any misuse or inappropriate
            behavior is solely your responsibility.
          </Text>
          <Text className="ml-2 mt-2 text-lg text-gray-100">
            • <Text className="font-semibold">Privacy Matters:</Text> We respect your privacy and do
            not retain chat data unless required for app functionality. Please avoid sharing
            sensitive personal information.
          </Text>
        </View>
      </ScrollView>

      <View className="mb-4 mt-auto px-6">
        <TouchableOpacity
          className="rounded-lg bg-white p-4"
          onPress={() => router.push('/onboarding/gender' as RelativePathString)}>
          <Text className="text-center text-lg font-bold text-black">Next</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}
